version: '3.4'
services:
  ovpn_client:
    image: minixxie/ovpn-client:0.0.1
    build: .
    container_name: ovpn_client
    hostname: ovpn_client
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    dns: 8.8.8.8
    volumes:
      - "./config.ovpn:/config.ovpn"
